### ISSUE TITLE
1.4.6 iOS Simulator / Devices broken

### ISSUE THREAD

**Issue by felipe-nrscorps** [yepher/CoreDataUtility#40]
Having some critical problems here...
1. In 1.4(6) the Devices list has multiple entries for the same Simulator. Do we need to reload the Devices list each time?
2. When opening a Device type (iPad Retina) the app is not found. Opening the second instance of the same Device yields similar results. Any ideas? 

Love your tool. Thanks in advance for your help.

**Comment by yepher** [comment]
Felipe,

Thanks for the feedback. I will investigate it.

Feel free to patch it and send me a pull request if you get to it first.

**Comment by yepher** [comment]
This has been fixed in this release: https://github.com/yepher/CoreDataUtility/releases/tag/1.5_9
