### ISSUE TITLE
First record has all Null column values in all Entity fetches

### ISSUE THREAD

**Issue by gantaa** [yepher/CoreDataUtility#42]
Me again :)  This tool has been very helpful identifying my own CoreData problems, so thanks again.

Please see these screenshots below.  In each of my entity tables, the first record has all NULL values.  I believe that this is a display problem with CoreDataPro, as my app is behaving correctly and there are no validation errors anymore saving the context.  I forked the repo and was going to try an debug it on my own and send a pull request, but my Dev team is not part of the Mac developer program (only iOS), so I'd have to pay $99 to help you debug this :)

Let me know if you've seen this before or if you need more info from me.

![image1]
(http://i.imgur.com/XvPtaEp.png)

![image2]
(http://i.imgur.com/YnsipFg.png)

![image3]
(http://i.imgur.com/cOpeRQ2.png)

**Comment by yepher** [comment]
Not sure why but I can't see the screen shots. 

It will be easiest to debug if you can send me your persistence file and the momd that demonstrate the problem.

You can email them too me at "github [at] Yepher.com". To find the files just open them the way you normally do and then use "File->Show Store in Finder" and "File->Show Model in Finder". If you don't mind to set the screen shots along to that will help.

**Comment by gantaa** [comment]
Sorry.  I updated the screen shots in my original post. And, I emailed the mom and persistence files for you.  Thanks

**Comment by yepher** [comment]
@gantaa thanks for reporting this. I just pushed a new release that resolves this issue.
