### ISSUE TITLE
Show the iOS version for simulator devices

### ISSUE THREAD

**Issue by mark-anders** [yepher/CoreDataUtility#43]
First - THANK YOU for creating this app and for updating it through Apple's changes to how simulators are stored.  It's incredibly hard to figure out where to find one's app with the XCode 6 changes.

When I am attempting to select my app, I get a list of devices such as "iPad Retina", "iPhone 5", etc, and the list repeats, I assume for different versions of iOS.  

It would be great if you could list the version of iOS along with the device as currently I have to hunt through the list for each instance of the device I'm testing against looking for my app.

**Comment by yepher** [comment]
Mark,

Agreed it is a very important feature to add. If you want to add it and give a pull request I will merge it in. Otherwise I will try and get to it in the next week or so.
